apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- infrastructure.cluster.x-k8s.io_shoots.yaml

labels:
- includeSelectors: false
  pairs:
      cluster.x-k8s.io/v1beta1: v1alpha1
